---
#Install updates on all
- name: Install updates on all
  hosts: all
  strategy: free
  tasks:
    - name: search and install updates
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
        reboot: yes
        reboot_timeout: 600
        log_path: c:\windows\logs\ansible_update_log.txt
      register: update_result
